### ISSUE TITLE
Do we need to compensate FCS when reading them into R?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [NKInstinct/flowGate#4]
Hi there, 

Thanks for a great package. 

I am more familiar with analysing spectral flow data when we import directly "Unmixed" FCS into R and thus no need for compensation in R. 

I noticed in the tutorial there is a compensation step. I was hoping to confirm whether we would need to perform compensation in R after we imported the FCS files which were likely compensated already during acquisition by traditional cytometer, e.g., Fortessa? Or, how might one check whether the imported data are compensated?

Thank you!

**Comment by NKInstinct** [comment]
Hi there - sorry, didn't see this until now. If you have an acquisition-defined comp matrix associated with your fcs files (i.e. you did compensation on the instrument itself, like you say), you don't need to re-compensate the data. You can check this for sure by calling `spillover()` on one of your samples, i.e.:

`spillover(gs[[1]])` 

where gs is some GatingSet object and gs[[1]] is the first sample in it.

That command will show a few different slots (one called spillover, one called $SPIL, etc) - if at least one of these slots has a matrix in it, your data have a comp matrix associated with them, and you just need to apply it to the GatingSet. See the FlowGate Vignette under "Acquisition-Defined Comp" for an example of how to do this (or have a look at the FlowCore and FlowWorkspace documentation if you want the full details). You can also do a quick sanity check on the data themselves - if you've got two fluorochromes with decent spectral overlap, you'll likely see some obvious under-comp artifacts in the data if the matrix hasn't been applied correctly.

Hope that helps!

**Comment by denvercal1234GitHub** [comment]
When I ran `flowCore::spillover(gs)`, it returned an error actually as below:

```
> spillover(sce_backboneClustering_fs_sample_id_gs[[1]])
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘spillover’ for signature ‘"GatingHierarchy"’
```
